<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_postal_code</name>
   <tag></tag>
   <elementGuidId>a93c3df9-79ab-428a-8b3c-6cd4a2bb90d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@class=&quot;input&quot;]//*[@data-reactid=&quot;.0.0.1.0.3.0.0.5.1.0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
